f = File.new('app/assets/images/weddingtoppers/CUP1.jpg')
WeddingTopping.create(code: "CUP1", name: "Arrastrando al Novio", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP2.jpg')
WeddingTopping.create(code: "CUP2", name: "De la mano", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP3.jpg')
WeddingTopping.create(code: "CUP3", name: "Marino", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP4.jpg')
WeddingTopping.create(code: "CUP4", name: "Curaditos", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP5.jpg')
WeddingTopping.create(code: "CUP5", name: "De Viaje", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP6.jpg')
WeddingTopping.create(code: "CUP6", name: "Alegres", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP7.jpg')
WeddingTopping.create(code: "CUP7", name: "Con mi club favorito", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP8.jpg')
WeddingTopping.create(code: "CUP8", name: "Escalando", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP9.jpg')
WeddingTopping.create(code: "CUP9", name: "Montañismo", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP10.jpg')
WeddingTopping.create(code: "CUP10", name: "Sorpresa", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP11.jpg')
WeddingTopping.create(code: "CUP11", name: "De la mano 2", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP12.jpg')
WeddingTopping.create(code: "CUP12", name: "Antigua", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP13.jpg')
WeddingTopping.create(code: "CUP13", name: "Clásico", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP14.jpg')
WeddingTopping.create(code: "CUP14", name: "Rosa en la boca", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP15.jpg')
WeddingTopping.create(code: "CUP15", name: "Antigua", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP16.jpg')
WeddingTopping.create(code: "CUP16", name: "En auto", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP17.jpg')
WeddingTopping.create(code: "CUP17", name: "Ositos", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP18.jpg')
WeddingTopping.create(code: "CUP18", name: "Chaqueta Blanca", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP19.jpg')
WeddingTopping.create(code: "CUP19", name: "Curaditos", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP20.jpg')
WeddingTopping.create(code: "CUP20", name: "En Corazón", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP21.jpg')
WeddingTopping.create(code: "CUP21", name: "Tipo Soft", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP22.jpg')
WeddingTopping.create(code: "CUP22", name: "Militar", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP23.jpg')
WeddingTopping.create(code: "CUP23", name: "De la mano 3", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP24.jpg')
WeddingTopping.create(code: "CUP24", name: "Chanchito", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP25.jpg')
WeddingTopping.create(code: "CUP25", name: "Rene y Piggy", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP26.jpg')
WeddingTopping.create(code: "CUP26", name: "Sentados y abrazados", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP27.jpg')
WeddingTopping.create(code: "CUP27", name: "El extraño mundo de Jack", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP28.jpg')
WeddingTopping.create(code: "CUP28", name: "Sobre el piano", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP29.jpg')
WeddingTopping.create(code: "CUP29", name: "Madera", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP30.jpg')
WeddingTopping.create(code: "CUP30", name: "Patitos", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP31.jpg')
WeddingTopping.create(code: "CUP31", name: "Onda Disco", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP32.jpg')
WeddingTopping.create(code: "CUP32", name: "En Brazo", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP33.jpg')
WeddingTopping.create(code: "CUP33", name: "Reventados", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP34.jpg')
WeddingTopping.create(code: "CUP34", name: "De la corbata", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP35.jpg')
WeddingTopping.create(code: "CUP35", name: "Aviador", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP36.jpg')
WeddingTopping.create(code: "CUP36", name: "Osito y Koala", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP37.jpg')
WeddingTopping.create(code: "CUP37", name: "Sentados", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP38.jpg')
WeddingTopping.create(code: "CUP38", name: "Gatitos", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP39.jpg')
WeddingTopping.create(code: "CUP39", name: "Carabinero en auto", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP40.jpg')
WeddingTopping.create(code: "CUP40", name: "Bebes", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP41.jpg')
WeddingTopping.create(code: "CUP41", name: "En Moto", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP42.jpg')
WeddingTopping.create(code: "CUP42", name: "Los Simpson", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP43.jpg')
WeddingTopping.create(code: "CUP43", name: "Sentado en Banca", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP44.jpg')
WeddingTopping.create(code: "CUP44", name: "Encadenado", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP45.jpg')
WeddingTopping.create(code: "CUP45", name: "Pescado", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP46.jpg')
WeddingTopping.create(code: "CUP46", name: "De armas tomar", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP47.jpg')
WeddingTopping.create(code: "CUP47", name: "Ositos Polares", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP48.jpg')
WeddingTopping.create(code: "CUP48", name: "Antes de arrancar", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP49.jpg')
WeddingTopping.create(code: "CUP49", name: "Románticos", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP50.jpg')
WeddingTopping.create(code: "CUP50", name: "Pisando el vestido", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP51.jpg')
WeddingTopping.create(code: "CUP51", name: "Ositos sobre luna", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP52.jpg')
WeddingTopping.create(code: "CUP52", name: "Demonio de Tazmania", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP53.jpg')
WeddingTopping.create(code: "CUP53", name: "Curaditos", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP54.jpg')
WeddingTopping.create(code: "CUP54", name: "En banquito", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP55.jpg')
WeddingTopping.create(code: "CUP55", name: "Japonés", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP56.jpg')
WeddingTopping.create(code: "CUP56", name: "Besito", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP57.jpg')
WeddingTopping.create(code: "CUP57", name: "Al hombro", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP58.jpg')
WeddingTopping.create(code: "CUP58", name: "Por celular", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP59.jpg')
WeddingTopping.create(code: "CUP59", name: "Abogados Presos", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP60.jpg')
WeddingTopping.create(code: "CUP60", name: "Románticos", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP61.jpg')
WeddingTopping.create(code: "CUP61", name: "Pintor", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP62.jpg')
WeddingTopping.create(code: "CUP62", name: "Sr. y Sra. cara de papa", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP63.jpg')
WeddingTopping.create(code: "CUP63", name: "Románticos 3", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP64.jpg')
WeddingTopping.create(code: "CUP64", name: "Velero", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP65.jpg')
WeddingTopping.create(code: "CUP65", name: "Violinista", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP66.jpg')
WeddingTopping.create(code: "CUP66", name: "Juntitos", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP67.jpg')
WeddingTopping.create(code: "CUP67", name: "Titanic", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP68.jpg')
WeddingTopping.create(code: "CUP68", name: "A la rastra", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP69.jpg')
WeddingTopping.create(code: "CUP69", name: "Vaquita", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP70.jpg')
WeddingTopping.create(code: "CUP70", name: "A lapa", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP71.jpg')
WeddingTopping.create(code: "CUP71", name: "Mecánico y veterinaria", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP72.jpg')
WeddingTopping.create(code: "CUP72", name: "Lo llevan", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP73.jpg')
WeddingTopping.create(code: "CUP73", name: "Ratoncitos pintores", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP74.jpg')
WeddingTopping.create(code: "CUP74", name: "Detective", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP75.jpg')
WeddingTopping.create(code: "CUP75", name: "En familia", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP76.jpg')
WeddingTopping.create(code: "CUP76", name: "Góticos", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP77.jpg')
WeddingTopping.create(code: "CUP77", name: "Chanchitos Play Boy", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP78.jpg')
WeddingTopping.create(code: "CUP78", name: "Playa", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP79.jpg')
WeddingTopping.create(code: "CUP79", name: "Motoqueros", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP80.jpg')
WeddingTopping.create(code: "CUP80", name: "Huasitos", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP81.jpg')
WeddingTopping.create(code: "CUP81", name: "De rodillas", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP82.jpg')
WeddingTopping.create(code: "CUP82", name: "En el cine", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP83.jpg')
WeddingTopping.create(code: "CUP83", name: "Al estrado", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP84.jpg')
WeddingTopping.create(code: "CUP84", name: "Payasitos", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP85.jpg')
WeddingTopping.create(code: "CUP85", name: "De compras y juego", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP86.jpg')
WeddingTopping.create(code: "CUP86", name: "Elvis", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP87.jpg')
WeddingTopping.create(code: "CUP87", name: "Chanchitos", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP88.jpg')
WeddingTopping.create(code: "CUP88", name: "Mariposas", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP89.jpg')
WeddingTopping.create(code: "CUP89", name: "Juntitos", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP90.jpg')
WeddingTopping.create(code: "CUP90", name: "Mario Bros", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP91.jpg')
WeddingTopping.create(code: "CUP91", name: "Star Wars", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP92.jpg')
WeddingTopping.create(code: "CUP92", name: "Onda Disco", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP93.jpg')
WeddingTopping.create(code: "CUP93", name: "Japones", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP94.jpg')
WeddingTopping.create(code: "CUP94", name: "Camiseta Selección", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP95.jpg')
WeddingTopping.create(code: "CUP95", name: "Hippies", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP96.jpg')
WeddingTopping.create(code: "CUP96", name: "Bajito", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP97.jpg')
WeddingTopping.create(code: "CUP97", name: "Auto a la antigua", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP98.jpg')
WeddingTopping.create(code: "CUP98", name: "Huasitos de Salón", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP99.jpg')
WeddingTopping.create(code: "CUP99", name: "Baterista y cantante", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP100.jpg')
WeddingTopping.create(code: "CUP100", name: "Obligado", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP101.jpg')
WeddingTopping.create(code: "CUP101", name: "Estrella de Mar", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP102.jpg')
WeddingTopping.create(code: "CUP102", name: "De armas tomar", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP103.jpg')
WeddingTopping.create(code: "CUP103", name: "Cabina inglesa", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP104.jpg')
WeddingTopping.create(code: "CUP104", name: "Sirenita y Buzo", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP105.jpg')
WeddingTopping.create(code: "CUP105", name: "Compradora Compulsiva", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP106.jpg')
WeddingTopping.create(code: "CUP106", name: "Polera Cómic", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP107.jpg')
WeddingTopping.create(code: "CUP107", name: "Auto Antiguo", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP108.jpg')
WeddingTopping.create(code: "CUP108", name: "En la playa", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP109.jpg')
WeddingTopping.create(code: "CUP109", name: "Rapunzel", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP110.jpg')
WeddingTopping.create(code: "CUP110", name: "M & M", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP111.jpg')
WeddingTopping.create(code: "CUP111", name: "Ojitos bien Cerrados", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP112.jpg')
WeddingTopping.create(code: "CUP112", name: "Los piratas del Caribe", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP113.jpg')
WeddingTopping.create(code: "CUP113", name: "Por si las moscas", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP114.jpg')
WeddingTopping.create(code: "CUP114", name: "Gope", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP115.jpg')
WeddingTopping.create(code: "CUP115", name: "Militar", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP116.jpg')
WeddingTopping.create(code: "CUP116", name: "Mineros", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP117.jpg')
WeddingTopping.create(code: "CUP117", name: "En la banca", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP118.jpg')
WeddingTopping.create(code: "CUP118", name: "Pinguino", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP119.jpg')
WeddingTopping.create(code: "CUP119", name: "Amigas", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP120.jpg')
WeddingTopping.create(code: "CUP120", name: "En sus piernas", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP121.jpg')
WeddingTopping.create(code: "CUP121", name: "Homosexuales", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP122.jpg')
WeddingTopping.create(code: "CUP122", name: "UP", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP123.jpg')
WeddingTopping.create(code: "CUP123", name: "Sandwish", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP124.jpg')
WeddingTopping.create(code: "CUP124", name: "Informal", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP125.jpg')
WeddingTopping.create(code: "CUP125", name: "Condorito", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP126.jpg')
WeddingTopping.create(code: "CUP126", name: "Trekking", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP127.jpg')
WeddingTopping.create(code: "CUP127", name: "Harley Davison", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP128.jpg')
WeddingTopping.create(code: "CUP128", name: "La bella y la bestia", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP129.jpg')
WeddingTopping.create(code: "CUP129", name: "Star Wars", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP130.jpg')
WeddingTopping.create(code: "CUP130", name: "Aeromoza", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP131.jpg')
WeddingTopping.create(code: "CUP131", name: "Surf", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP132.jpg')
WeddingTopping.create(code: "CUP132", name: "Playa", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP133.jpg')
WeddingTopping.create(code: "CUP133", name: "Bomberos", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP134.jpg')
WeddingTopping.create(code: "CUP134", name: "Detenido", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP135.jpg')
WeddingTopping.create(code: "CUP135", name: "Camiseta", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP136.jpg')
WeddingTopping.create(code: "CUP136", name: "Japones 3", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP137.jpg')
WeddingTopping.create(code: "CUP137", name: "Aviador", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP138.jpg')
WeddingTopping.create(code: "CUP138", name: "Amarrado dice SI", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP139.jpg')
WeddingTopping.create(code: "CUP139", name: "Abrazados", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP140.jpg')
WeddingTopping.create(code: "CUP140", name: "Entrevistando", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP141.jpg')
WeddingTopping.create(code: "CUP141", name: "Chinitos", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP142.jpg')
WeddingTopping.create(code: "CUP142", name: "Metal", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP143.jpg')
WeddingTopping.create(code: "CUP143", name: "Cadaver", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP144.jpg')
WeddingTopping.create(code: "CUP144", name: "Safari", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP145.jpg')
WeddingTopping.create(code: "CUP145", name: "En Familia", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP146.jpg')
WeddingTopping.create(code: "CUP146", name: "Pinguino", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP147.jpg')
WeddingTopping.create(code: "CUP147", name: "Ballet", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP148.jpg')
WeddingTopping.create(code: "CUP148", name: "Hip Hop", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP149.jpg')
WeddingTopping.create(code: "CUP149", name: "Con Mascotas", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP150.jpg')
WeddingTopping.create(code: "CUP150", name: "Cantante", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP151.jpg')
WeddingTopping.create(code: "CUP151", name: "Tortugas de Mar", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP152.jpg')
WeddingTopping.create(code: "CUP152", name: "Hipopótamos", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP153.jpg')
WeddingTopping.create(code: "CUP153", name: "Salchichas", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP154.jpg')
WeddingTopping.create(code: "CUP154", name: "Zorritos", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP155.jpg')
WeddingTopping.create(code: "CUP155", name: "Elefantes", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP156.jpg')
WeddingTopping.create(code: "CUP156", name: "Patitos", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP157.jpg')
WeddingTopping.create(code: "CUP157", name: "Dinosaurios", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP158.jpg')
WeddingTopping.create(code: "CUP158", name: "Brontosaurius", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP159.jpg')
WeddingTopping.create(code: "CUP159", name: "Argentina Chile", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP160.jpg')
WeddingTopping.create(code: "CUP160", name: "Gloria y Moto Moto", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP161.jpg')
WeddingTopping.create(code: "CUP161", name: "Chinitos", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP162.jpg')
WeddingTopping.create(code: "CUP162", name: "ONU", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP163.jpg')
WeddingTopping.create(code: "CUP163", name: "UP jovenes", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP164.jpg')
WeddingTopping.create(code: "CUP164", name: "Modernos", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP165.jpg')
WeddingTopping.create(code: "CUP165", name: "Piratas", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP166.jpg')
WeddingTopping.create(code: "CUP166", name: "Paris", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP167.jpg')
WeddingTopping.create(code: "CUP167", name: "Garfield", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP168.jpg')
WeddingTopping.create(code: "CUP168", name: "De la mano 4", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP169.jpg')
WeddingTopping.create(code: "CUP169", name: "De la mano 5", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP170.jpg')
WeddingTopping.create(code: "CUP170", name: "Bailando", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP171.jpg')
WeddingTopping.create(code: "CUP171", name: "Sidecar", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP172.jpg')
WeddingTopping.create(code: "CUP172", name: "Románticos", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP173.jpg')
WeddingTopping.create(code: "CUP173", name: "Entregando el corazón", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP174.jpg')
WeddingTopping.create(code: "CUP174", name: "De mochila", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP175.jpg')
WeddingTopping.create(code: "CUP175", name: "Ardillas", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP176.jpg')
WeddingTopping.create(code: "CUP176", name: "Brazos Abiertos", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP177.jpg')
WeddingTopping.create(code: "CUP177", name: "Mapuches", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP178.jpg')
WeddingTopping.create(code: "CUP178", name: "Saludando", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP179.jpg')
WeddingTopping.create(code: "CUP179", name: "En el Caño", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP180.jpg')
WeddingTopping.create(code: "CUP180", name: "Ositos Polares", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP181.jpg')
WeddingTopping.create(code: "CUP181", name: "Susanita y Felipe", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP182.jpg')
WeddingTopping.create(code: "CUP182", name: "Civil", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP183.jpg')
WeddingTopping.create(code: "CUP183", name: "Románticos 2", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP184.jpg')
WeddingTopping.create(code: "CUP184", name: "Bomberos", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP185.jpg')
WeddingTopping.create(code: "CUP185", name: "Comando", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP186.jpg')
WeddingTopping.create(code: "CUP186", name: "Paseando a los perros", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP187.jpg')
WeddingTopping.create(code: "CUP187", name: "Ratones", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP188.jpg')
WeddingTopping.create(code: "CUP188", name: "Chucky", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP189.jpg')
WeddingTopping.create(code: "CUP189", name: "Minions", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP190.jpg')
WeddingTopping.create(code: "CUP190", name: "Futbolero", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP191.jpg')
WeddingTopping.create(code: "CUP191", name: "Floreal", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP192.jpg')
WeddingTopping.create(code: "CUP192", name: "UP jóvenes 2", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP193.jpg')
WeddingTopping.create(code: "CUP193", name: "Juntitos", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP194.jpg')
WeddingTopping.create(code: "CUP194", name: "Paris 2", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP195.jpg')
WeddingTopping.create(code: "CUP195", name: "Sentados", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP196.jpg')
WeddingTopping.create(code: "CUP196", name: "Cool", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP197.jpg')
WeddingTopping.create(code: "CUP197", name: "Lila", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP198.jpg')
WeddingTopping.create(code: "CUP198", name: "Love", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP199.jpg')
WeddingTopping.create(code: "CUP199", name: "Abrazados", image: f)
f.close()
f = File.new('app/assets/images/weddingtoppers/CUP200.jpg')
WeddingTopping.create(code: "CUP200", name: "Popeye", image: f)
f.close()
